spring:
  datasource:
    url: jdbc:postgresql://db.kkqmcdsnodnidwkqjrxe.supabase.co:5432/postgres
    username: postgres
    password: surajpro555@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
server:
  port: 9000
  error:
    path: /user/error
    whitelabel:
      enabled: false
